language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
before_deploy:
- npm run clean
- npm run build:prod
- npm install jshon
- export RELEASE_NOTES=$(npx jshon -s "$(cat RELEASE-NOTES.md)")
deploy:
- provider: npm
  email: biju.joseph@semanticbits.com
  skip_cleanup: true
  api_key:
    secure: d81eBLKFMz5Ap8msK0SsI1i9+FTUWGko9ym4LZrb/OFzTKPI2W0SzsofS9x2ftclAwz/G7Ua8DN9qJIYH5Cz5gYue2XBaNWNhVmEtWNNPoR0U/WhXXaEZdSZXgXbxKFyZOcA5jM8I+nbpGkNIhkwytgnifuCpR+wmAgQGnnbTb4vcNeJ8+CZtlQgQq63Cx1zShvugyoBqKNXvqe/oRSDWCh2HjWKdl0p5zdRRZhDO3Lv1EFborsC55wps/63v0iQ8Uea8YDMS1Y5z0I4hw0asLNA/cYiPeCAB0kwbhPQvrE8mK/vA9o33VlIjZ9CHhjTxno82mJlDKA8qvRommXfjmSDy/NwNiManTWz6o4H/Pb1v5b7SlByommpS40uT5U/s2eBNf91pBaAvGXcxX9bClduzV/7xdhGBRS0WtTVGj0tEmsdcSYTaTqnAibCWqeKn37DU/7mcgrRBl/TfBiOQsRJxaeHakRrKm42+9y11KIdbVF7WmCDgJD0bZsjA4RmMz8fFgiXM839QLH82GvVaQZZkiOb6mPbBEp8ApS1UrhIQrAct2oRQy4x1dnRovsafObG8mAr8GerUqffixX276faqfoATA8F8dc1Sp3+MBPAV1oIE3CUQLUCDuRM8A0UQDEg6PKfvcyPswDIhfCl1R68q4yDXdwfnO5rbLX671E=
  on:
    tags: true
    repo: CMSgov/qpp-file-upload-api-client
- provider: releases
  api_key:
    secure: mZB/nXEpclGM1ClBJQ9mEMSyi9vUrC6I/SceSg9Q5gKTP+aFjVMvtUnMso9iYOPyxVD+gdfgGDiLAdbQr1MitM1n1103vUab6QPhXFFWrBk/QzZ81a9PA9oeSTQevkv9C2FNJTvoH5t5A2iuKjUYyR+3IWfQRYaKMUX2py5DGFX/X1b/JCDYJopmsm91Pa51I3A3VVWqr+6OdqxVacl76++J63iFHqO60SaY4/QAzTvbUn7PTBY54XpHYmrGd0PrqKzgRA4gc7aSeqxc2b31XrC3ALw52sNjELaTkkLQI6njF/93pHrlmlWzaYjWM0Mqo+1nBUgM6UYGyEifnSM9fu5wFRAGImDq/NqqtyO70unbAADInpTkI5ONf+LCWol+NgHPse+qlDf9/FFu7am0N2XOvmFstMAIdA4cU7n4x3ntFghFCBpHWfkb1n+I8cRGYecqF9wfcQAfnYDa+Pr0k+I3j0S5K+JNmuwRTkKvyvzoBsqgjWTxlnPuhfoRa2zTRIp7iyx9uEV3dG+p2cp8XEi2ANsK5wY6BBFvXGP8EnHS/kIcRfadXxXyxXIAV94PWSHCufwx/JSpSIiMo0eejzMqBGBXgE7NVtbQJSnrCzDU1O5e/s8u4oazeWWx91AFNBlG2YYnqjrhrbIcKZK0c4yoGdZavx5XixSgLAC6rf0=
  file: RELEASE-NOTES.md
  body: "${RELEASE_NOTES}"
  draft: false
  prerelease: true
  on:
    repo: CMSgov/qpp-file-upload-api-client
    tags: true
env:
  global:
    secure: I7nwK646qNB+ezeoN3bZRk6NWxQUdNNFVw5LyrPaeVwooXlK90TVNHg5W+aW17lee6S3BcTK/ux207ylPVJXbW/BUHvNZVrrKAapW45DEweUhnPsnz++kRN4mKtUUq59rF9VAC3cc/cArsJuni/sLNykFxE9lXnA3rSY9igeyuBw5S7QY5mW4eyO62tRFmYFuJPfVIXKOa6yDSXQ7MotdL4KjfGin6+odJPSVT6BwbGJ1xRMULunuOJr+69IaroCBtvexMoQsDhCvRx+sPELj7KFBpx7M6JyfWB2B0X2GTznqijihEUGxR2VTxXsj5mJvCDpMv5NiEdIuwRY6/2gDsP60uzvkSQPAcMQ5boWL0N3OhVR/rx+AzfaHGXeMq+iA6emB7I4gs09iSjHI+Q9Z9HU8rSaJc7AFiHBheaw4a5/UI0DKHJHcjKd+nePckWFQ2sJmAJ+Lm/LbreFhaPoEBmVTWo8SJCa4NJvtZMI7GsMWqTREA59P0Un0eiuUlBoqX0oPhmcY0W6fihGV9tjufVDIoCFYQmuhxlfIkr9xCF5ude8Ucoscq9eeNXJAEPrcU+k7R3/0GFoFaJ32n+FKo6o3KJkGdo4DoJuBHBwRazNBvzliOlbxnr4ojb2JQpvZ57SAUK4Ds0VrY96lt6mlCZafb8VEkFkw/FCPyuPnWE=
