language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
before_deploy:
  - npm run clean
  - npm run build:prod
deploy:
  provider: npm
  email: biju.joseph@semanticbits.com
  api_key:
    secure: X5WSSBMAaU0q2EWe5EQpwghZ/RE6Uo9CHAwoON5BOs6C+PTR0zGsT3RKN9Ec+r/fEST2Lvmdvl6Z6TuI9THiD61HQ2uZCon1PkTnXgO+cgg4tnorccAk2fyykOpxEttvetSVNuR/Zpqc2YT6NvwkPKYwK9cgmg2PHyqA0RM6VPQhDmukaMrNP/TtlWJp4w5cxZW78lfxDHnie/fMLfz/qfeF+xGwLV91cHdlzK4tNuug/2QfzlwUSzRMwgE7WnnGQUvJl+Kc//IXAVZj3aPtxl3aK5AxBH0bPacalafCSwlMzYLOR9JHrnHg6flM1gi1BcsxgdEiv2UPBWDT0A0DJTNHHmp1Fto3W8wtsnEWtnxVd08T9fAGhPuDtFknv1yDxPWG6CBCobro1Xphk5PLgu5Ixu3HM2y4sR0JIRZgwTA3qlGGsj1f0ZAPmhI75d5vulCLLOoOe9uO8jWbEeExcfoZtOhWrijYQ9sm8OhI3sauV6MCLt4M5pDqDwP669ZI6imXSTXdx+D2vjJCyuRsLoIECkplOGE+SCCd9wsoF7tkTQQIrDnZ8aT/YhDwsC4Fr3s/M4fJtkJMqtNf+7NFZMX2Sq5VajQLlTEnDXp9KnSAa2KVx69F4KWZyRD4yxCWLSdRkEoXMxnwQXyMgZmCF0UE5RThjg5a/vKZzgaJL8s=
  tag: next
  on:
    branch: master
    repo: CMSgov/qpp-file-upload-api-client
