language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
before_deploy:
  - npm run clean
  - npm run build:prod
  - npm install jshon
  - export RELEASE_NOTES=$(npx jshon -s "$(cat RELEASE-NOTES.md)")
deploy:
  - provider: npm
    email: biju.joseph@semanticbits.com
    api_key:
      secure: X5WSSBMAaU0q2EWe5EQpwghZ/RE6Uo9CHAwoON5BOs6C+PTR0zGsT3RKN9Ec+r/fEST2Lvmdvl6Z6TuI9THiD61HQ2uZCon1PkTnXgO+cgg4tnorccAk2fyykOpxEttvetSVNuR/Zpqc2YT6NvwkPKYwK9cgmg2PHyqA0RM6VPQhDmukaMrNP/TtlWJp4w5cxZW78lfxDHnie/fMLfz/qfeF+xGwLV91cHdlzK4tNuug/2QfzlwUSzRMwgE7WnnGQUvJl+Kc//IXAVZj3aPtxl3aK5AxBH0bPacalafCSwlMzYLOR9JHrnHg6flM1gi1BcsxgdEiv2UPBWDT0A0DJTNHHmp1Fto3W8wtsnEWtnxVd08T9fAGhPuDtFknv1yDxPWG6CBCobro1Xphk5PLgu5Ixu3HM2y4sR0JIRZgwTA3qlGGsj1f0ZAPmhI75d5vulCLLOoOe9uO8jWbEeExcfoZtOhWrijYQ9sm8OhI3sauV6MCLt4M5pDqDwP669ZI6imXSTXdx+D2vjJCyuRsLoIECkplOGE+SCCd9wsoF7tkTQQIrDnZ8aT/YhDwsC4Fr3s/M4fJtkJMqtNf+7NFZMX2Sq5VajQLlTEnDXp9KnSAa2KVx69F4KWZyRD4yxCWLSdRkEoXMxnwQXyMgZmCF0UE5RThjg5a/vKZzgaJL8s=
    on:
      tags: true
      repo: CMSgov/qpp-file-upload-api-client
  - provider: releases
    api_key:
      secure: lkGeo56RyVU6ecSRxvqYeVV8KEjPSBRn/o1ixiol31Eh3t0c+e8ZM9ophKhSl3QGOJpZ/rK44nGFsncsUc7PMx2k2z+7Xsn6xXwT4kkmte17ThfhXpcuoWDhQgkNO7QCb/lpG17gH3G468Px9DmF4ZWvepgC0OsCK8QAMcMjKTfl1TK3Z/prgx/TgP2H2lDhOCrPbn5ObPSTXH6l4GjWd1eW8KtYJiXenDLeEUcIpKuulm8bZ/zZ2a5lgXaPcIM+ZRx5W4jmoNCN27SwKG7w/urdLf+RmGCer/RnCMcuh5J9PyTPm0u5+iwi6bZr7vSbGjhlR2f6mKuB3+upa3aOMGYw72QRPUQVPJEZGOFER2XVmjG3BochZ8rw1xnQr6kTghiTP8+zdNGXfcsZo0+l+x23BSxUExfWNHFmPrGIKpd3Lcclf1Eo4ua1O+TV7OK5rzbJfIxtBSYp+eSbi/5cou3791oP+hYbDV9qfxYpnS4cnogGVBA7+BDyCV1bDA3wQNLJUEyN98RMOA2LNXNwMsvaYKAiEjgmx/Ao7Z944cD4Vza6CVhxE8ywzoKWl2iSy2N1jmSrJSSC8EfhkciahGR2R2TlXRE8eNB0CZAGl9AuPBWDUMwU0kmAuqFAfrNRz+1Cp9xKD1OaF3CD2Vop4ao5XTP7GcQ2gQLMkfDgw04=
    file: "RELEASE-NOTES.md"
    body: "${RELEASE_NOTES}"
    draft: true
    on:
      repo: CMSgov/qpp-file-upload-api-client
      tags: true