name: Continuous Integration Suite
on:
  push:
    branches:
      - develop
      - release/*
      - master
  pull_request:

jobs:
  build:
    name: Run unit and verification tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Setup Node.js  
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Clear the cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Run verification and unit tests
        run: npm run coverage

      - name: Create Cobertura coverage report
        uses: 5monkeys/cobertura-action@882bd919c67f7aa665370064c22fb81e7662a759 # pin@master
        with:
          path: coverage/cobertura-coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          only_changed_files: false
          show_line: true
          show_branch: true
          minimum_coverage: 80
