name: "Detect Hardcoded Secrets"

on:
  push: 

jobs:
  gitleaks:
    name: Scan for committed secrets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gitleaks-action
      uses: gitleaks/gitleaks-action@v1.6.0
