name: Deploy Beta version to NPM Registry

on:
  release:
    types: [ prereleased ]

jobs:

  publish-npm:
    name: Build library and deploy to NPM registry as a beta release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci          

      - name: Clean
        run: npm run clean

      - name: Do production build
        run: npm run build:prod

      - name: Publish beta version to NPMJS
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
